language: java
dist: xenial
# Skip install phase to avoid unwanted mvn build
before_install:    
    - sudo apt-get -y install maven
    - sudo apt-get -y install openjdk-8-jdk
    - export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
    
install: skip
# Run maven build in quiet mode to avoid log file limit in Travis CI.
# Only errors and Maven version information will be printed in the CI logs.
script: 
  - mvn clean install -B -V | grep -e "\[ERROR\]" -e Maven -e "// Start Running" -e "Building"; test ${PIPESTATUS[0]} -eq 0;
cache:
  directories:
  - $HOME/.m2
